version: "3"
services:

  django:
    build: .
    ports:
      - 8002:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.6-alpine3.18
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres